#!/bin/sh

set -e

size=$(wc -c < $1)

if [ "$size" -gt "510" ]; then # reserve space for 2 bytes
	printf "\e[1;31msize of $size bytes exceeded 512\e[0m\n"
	exit 1
else
	printf "\e[1;34m --- $1 $size --- \e[0m\n"
fi